export const info = {
    name: 'azure',
    icon: 'logo/azure.svg',
};

export enum Language {
    auto = '',
    zh_cn = 'zh-Hans',
    zh_tw = 'zh-Hant',
    en = 'en',
    ja = 'ja',
    ko = 'ko',
    fr = 'fr',
    es = 'es',
    ru = 'ru',
    de = 'de',
    it = 'it',
    tr = 'tr',
    pt_pt = 'pt-pt',
    pt_br = 'pt',
    vi = 'vi',
    id = 'id',
    th = 'th',
    ms = 'ms',
    ar = 'ar',
    hi = 'hi',
    mn_cy = 'mn-Cyrl',
    mn_mo = 'mn-Mong',
    km = 'km',
    nb_no = 'no',
    nn_no = 'no',
    fa = 'fa',
}
