import * as _system from './system';
import * as _tesseract from './tesseract';
import * as _baidu_ocr from './baidu';
import * as _baidu_accurate_ocr from './baidu_accurate';
import * as _iflytek_ocr from './iflytek';
import * as _tencent_ocr from './tencent';
import * as _tencent_accurate_ocr from './tencent_accurate';
import * as _volcengine_ocr from './volcengine';
import * as _volcengine_multi_lang_ocr from './volcengine_multi_lang';
import * as _doc2x from './doc2x';
import * as _microsoft_ocr from './microsoft_ocr';
import * as _baimiao_ocr from './baimiao_ocr';
import * as _qwen_ocr from './qwen_ocr';
import * as _rapid_ocr from './rapid_ocr';

export const system = _system;
export const tesseract = _tesseract;
export const baidu_ocr = _baidu_ocr;
export const baidu_accurate_ocr = _baidu_accurate_ocr;
export const iflytek_ocr = _iflytek_ocr;
export const tencent_ocr = _tencent_ocr;
export const tencent_accurate_ocr = _tencent_accurate_ocr;
export const volcengine_ocr = _volcengine_ocr;
export const volcengine_multi_lang_ocr = _volcengine_multi_lang_ocr;
export const doc2x = _doc2x;
export const microsoft_ocr = _microsoft_ocr;
export const baimiao_ocr = _baimiao_ocr;
export const qwen_ocr = _qwen_ocr;
export const rapid_ocr = _rapid_ocr;
